// Sample backlinks analysis data for investigation pages
// Two merchant records included: 1021893 and 1106835

export type BacklinksAnalysis = any;

export const backlinksSampleData: Record<number, BacklinksAnalysis> = {
  13492291: {
    total_backlinks: 11,
    total_links: 10,
    seo_analysis: {
      seo_domain_count: 4,
      seo_links_count: 7,
      seo_backlinks: 7,
      seo_backlinks_percentage: 63.64,
      seo_triggered: true,
      seo_overall_triggered: "Yes",
      seo_reasoning: "Both conditions for triggering SEO manipulation are met. First, there are 7 domains identified as having SEO/backlink-selling/PBN intent, which is greater than the minimum threshold of 2 domains. Second, these domains account for 63.64% of the total backlinks, which is well above the required 30% threshold. Some of the matched domains include 'analyticshaven.top' (matched by TLD '.top'), 'domaindexer.com' (matched by keyword 'index'), and '8coint.com' (matched by keyword 'coin'). This high concentration of backlinks from domains with SEO-manipulation signals strongly suggests an attempt to manipulate search rankings. Therefore, the trigger is set to Yes.",
      seo_matches: [
        {
          "domain": "analyticshaven.top",
          "match": ".top"
        },
        {
          "domain": "optimizeflow.top",
          "match": ".top"
        },
        {
          "domain": "blogsphere.top",
          "match": ".top"
        },
        {
          "domain": "dailymusings.top",
          "match": ".top"
        },
        {
          "domain": "drjack.world",
          "match": ".world"
        },
        {
          "domain": "domaindexer.com",
          "match": "index"
        },
        {
          "domain": "8coint.com",
          "match": "coin"
        }
      ],
      seo_manipulation_links: [
        {
          "Domain": "analyticshaven.top",
          "Domain ascore": 5,
          "category": null,
          "Backlinks": 1,
          "IP Address": "195.20.19.178",
          "First seen": "12h ago",
          "Last seen": "12h ago",
          "status": "new",
          "link_type": "nofollow",
          "_seo_match": ".top"
        },
        {
          "Domain": "optimizeflow.top",
          "Domain ascore": 5,
          "category": null,
          "Backlinks": 1,
          "IP Address": "195.20.19.178",
          "First seen": "5d ago",
          "Last seen": "5d ago",
          "status": "new",
          "link_type": "nofollow",
          "_seo_match": ".top"
        },
        {
          "Domain": "blogsphere.top",
          "Domain ascore": 5,
          "category": null,
          "Backlinks": 1,
          "IP Address": "195.20.19.178",
          "First seen": "6d ago",
          "Last seen": "6d ago",
          "status": "new",
          "link_type": "nofollow",
          "_seo_match": ".top"
        },
        {
          "Domain": "dailymusings.top",
          "Domain ascore": 5,
          "category": null,
          "Backlinks": 1,
          "IP Address": "195.20.19.178",
          "First seen": "12d ago",
          "Last seen": "12d ago",
          "status": "new",
          "link_type": "nofollow",
          "_seo_match": ".top"
        },
        {
          "Domain": "drjack.world",
          "Domain ascore": 25,
          "category": "Online Services",
          "Backlinks": 1,
          "IP Address": "195.20.19.178",
          "First seen": "Jan 19, 2026",
          "Last seen": "Jan 19, 2026",
          "status": null,
          "link_type": "nofollow",
          "_seo_match": ".world"
        },
        {
          "Domain": "domaindexer.com",
          "Domain ascore": 6,
          "category": null,
          "Backlinks": 1,
          "IP Address": "104.21.42.170",
          "First seen": "Dec 7, 2025",
          "Last seen": "Feb 27, 2026",
          "status": null,
          "link_type": "nofollow",
          "_seo_match": "index"
        },
        {
          "Domain": "8coint.com",
          "Domain ascore": 4,
          "category": null,
          "Backlinks": 1,
          "IP Address": "104.21.83.176",
          "First seen": "Dec 3, 2025",
          "Last seen": "4d ago",
          "status": null,
          "link_type": "nofollow",
          "_seo_match": "coin"
        }
      ]
    },
    risky_content_analysis: {
      risky_content_domain_count: 0,
      risky_links_count: 0,
      risky_links_backlinks: 0,
      risky_content_backlinks_percentage: 0.0,
      risky_recent_domains: 0,
      risky_triggered: "No",
      risky_overall_triggered: "No",
      risky_reasoning: "The analysis shows that there are 0 unique risky domains and 0 backlinks from risky domains, which means 0.0% of the total backlinks are from risky domains. This is well below the 20% threshold required for the first condition. Additionally, since there are no risky domains, the second condition (at least 2 risky domains seen in the last 90 days) is also not met. Therefore, neither of the required conditions are satisfied. No domains from the risky content list were matched in the backlink profile.",
      risk_links: [],
      risky_matches: []
    },
    low_credibility_analysis: {
      low_credibility_domain_count: 0,
      low_credibility_links_count: 0,
      low_credibility_backlinks: 0,
      low_credibility_backlinks_percentage: 0.0,
      low_credibility_avg_domain_authority: 0.0,
      low_credibility_triggered: "No",
      low_credibility_overall_triggered: "No",
      low_credibility_reasoning: "The backlink profile does not meet the trigger conditions. There are no backlinks from low-credibility domains using spammy TLDs such as '.info', '.pro', '.me', '.biz', '.ru', '.cn', '.tk', '.gq', '.cf', or '.ml'. The low credibility domains list is empty, with 0 unique domains and 0 backlinks, resulting in 0.0% of total backlinks coming from such sources. Additionally, the average domain authority score for these domains is 0.0, indicating no data. Since neither of the two required conditions are met\u2014there are no low-credibility backlinks and thus not \u226550% of total backlinks from such domains\u2014the trigger is not activated.",
      low_credibility_domains: []
    },
    high_authority_analysis: {
      high_authority_domains_count: 0,
      high_authority_triggered: "No",
      high_authority_overall_triggered: "No",
      high_authority_reasoning: "After analyzing the backlink profile, there are no domains with a Domain ascore of 70 or higher present in the backlink list. According to the criteria, a domain is considered high authority only if its Domain ascore is 70 or above. Since the high authority domains list is empty and the unique count is 0, there are no signals from high authority domains. Therefore, the trigger is set to 'No' because none of the backlinks come from high authority sources.",
      high_authority_domains: []
    },
    overall_analysis: {
      overall_trigger: "Yes",
      overall_reasoning: "The overall trigger is set to Yes because the 'seo_triggered' condition is True. This means that, even though the backlink is not from a high authority source and there are no signs of risky content or low credibility, the backlink appears to be created primarily for SEO purposes. In simple terms, the backlink looks like it was made just to improve search engine rankings rather than being a natural or editorial link. According to the logic, if any of the SEO, risky content, or low credibility signals are present (and high authority is not), the trigger is activated. Therefore, the backlink profile is flagged due to SEO-driven characteristics."
    },
    data: [
      {
        "Domain": "analyticshaven.top",
        "Domain ascore": 5,
        "category": null,
        "Backlinks": 1,
        "IP Address": "195.20.19.178",
        "First seen": "12h ago",
        "Last seen": "12h ago",
        "status": "new",
        "link_type": "nofollow",
        "_seo_match": ".top"
      },
      {
        "Domain": "optimizeflow.top",
        "Domain ascore": 5,
        "category": null,
        "Backlinks": 1,
        "IP Address": "195.20.19.178",
        "First seen": "5d ago",
        "Last seen": "5d ago",
        "status": "new",
        "link_type": "nofollow",
        "_seo_match": ".top"
      },
      {
        "Domain": "blogsphere.top",
        "Domain ascore": 5,
        "category": null,
        "Backlinks": 1,
        "IP Address": "195.20.19.178",
        "First seen": "6d ago",
        "Last seen": "6d ago",
        "status": "new",
        "link_type": "nofollow",
        "_seo_match": ".top"
      },
      {
        "Domain": "dailymusings.top",
        "Domain ascore": 5,
        "category": null,
        "Backlinks": 1,
        "IP Address": "195.20.19.178",
        "First seen": "12d ago",
        "Last seen": "12d ago",
        "status": "new",
        "link_type": "nofollow",
        "_seo_match": ".top"
      },
      {
        "Domain": "screenshots.wiki",
        "Domain ascore": 5,
        "category": null,
        "Backlinks": 1,
        "IP Address": "195.20.19.178",
        "First seen": "Mar 11, 2026",
        "Last seen": "Mar 11, 2026",
        "status": null,
        "link_type": "nofollow"
      },
      {
        "Domain": "urls-shortener.eu",
        "Domain ascore": 5,
        "category": null,
        "Backlinks": 2,
        "IP Address": "195.20.19.178",
        "First seen": "Feb 5, 2026",
        "Last seen": "Mar 11, 2026",
        "status": null,
        "link_type": "nofollow"
      },
      {
        "Domain": "drjack.world",
        "Domain ascore": 25,
        "category": "Online Services",
        "Backlinks": 1,
        "IP Address": "195.20.19.178",
        "First seen": "Jan 19, 2026",
        "Last seen": "Jan 19, 2026",
        "status": null,
        "link_type": "nofollow",
        "_seo_match": ".world"
      },
      {
        "Domain": "domaindexer.com",
        "Domain ascore": 6,
        "category": null,
        "Backlinks": 1,
        "IP Address": "104.21.42.170",
        "First seen": "Dec 7, 2025",
        "Last seen": "Feb 27, 2026",
        "status": null,
        "link_type": "nofollow",
        "_seo_match": "index"
      },
      {
        "Domain": "toplikevideo.com",
        "Domain ascore": 2,
        "category": null,
        "Backlinks": 1,
        "IP Address": "172.67.142.172",
        "First seen": "Dec 5, 2025",
        "Last seen": "10d ago",
        "status": null,
        "link_type": "nofollow"
      },
      {
        "Domain": "8coint.com",
        "Domain ascore": 4,
        "category": null,
        "Backlinks": 1,
        "IP Address": "104.21.83.176",
        "First seen": "Dec 3, 2025",
        "Last seen": "4d ago",
        "status": null,
        "link_type": "nofollow",
        "_seo_match": "coin"
      }
    ]
  },
  1106835: {
    seo_analysis: {
      seo_domain_count: 13,
      seo_links_count: 43,
      seo_backlinks: 48,
      seo_backlinks_percentage: 10.41,
      seo_triggered: false,
      seo_overall_triggered: "No",
      seo_reasoning:
        "The backlink profile was analyzed for evidence of search ranking manipulation using two rule-based criteria: (1) the number of SEO/backlink-selling/PBN-intent domains must be at least 4, and (2) backlinks from these domains must make up at least 30% of the total backlinks. In this case, while there are 13 such domains (e.g., 'seoprobox.click' with _seo_match 'seo', 'backlinkdirectory.site' with _seo_match 'backlink', 'sunnyside-pbn-domains.club' with _seo_match 'pbn', 'who-wants-pbn-links.xyz' with _seo_match 'links'), the percentage of backlinks from these domains is only 10.41%, which is below the 30% threshold. Therefore, since the second condition is not met, the trigger for SEO manipulation is set to 'No'.",
      seo_matches: [
        { domain: "global-ranks.pages.dev", match: "rank" },
        { domain: "kingranks.com", match: "rank" },
        { domain: "seoprobox.click", match: "seo" },
        { domain: "takes.sbs", match: ".sbs" },
        { domain: "wants.cfd", match: ".cfd" },
        { domain: "backlink.co.in", match: "backlink" },
        { domain: "backlinkdirectory.site", match: "backlink" },
        { domain: "backlinks-checker.com", match: "backlink" },
        { domain: "backlinksources.com", match: "backlink" },
        { domain: "best-seo-domains.com", match: "seo" },
        { domain: "blinks.monster", match: "links" },
        { domain: "blinks.sbs", match: "links" },
        {
          domain: "boost-your-site-with-homepage-backlinks.us",
          match: "backlink",
        },
        { domain: "browse-all-expired-domains.com", match: "expired" },
        { domain: "browseallexpireddomains.us", match: "expired" },
        { domain: "creativeposts.top", match: ".top" },
        { domain: "dailymusings.top", match: ".top" },
        {
          domain: "domains-links-backlinks-all-for-purchase.homes",
          match: "backlink",
        },
        { domain: "dr70-links.co.uk", match: "links" },
        { domain: "drjack.world", match: ".world" },
        { domain: "ever-heard-of-homepage-backlinks.bond", match: "backlink" },
        { domain: "financialvideos.club", match: ".club" },
        { domain: "full-expired-domain-lists.us", match: "expired" },
        { domain: "great-choice-for-pbn-domains.co.uk", match: "pbn" },
        { domain: "indonesia-gov-links.eu", match: "links" },
        { domain: "knows.sbs", match: ".sbs" },
        { domain: "linksdirectory.in", match: "links" },
        { domain: "metamagic.top", match: ".top" },
        { domain: "newest-expired-domains-here.click", match: "expired" },
        { domain: "optimizeflow.top", match: ".top" },
        { domain: "rankingway.site", match: "rank" },
        { domain: "seo-revealed.club", match: "seo" },
        { domain: "seoboast.site", match: "seo" },
        { domain: "sunnyside-pbn-domains.club", match: "pbn" },
        { domain: "takes.homes", match: ".homes" },
        { domain: "thebestbacklinksavailable.click", match: "backlink" },
        { domain: "webranksite.com", match: "rank" },
        { domain: "webranksofworld.site", match: "rank" },
        { domain: "what-happens-next.xyz", match: ".xyz" },
        { domain: "who-wants-pbn-links.xyz", match: "links" },
        { domain: "worldclasspbnlinks.biz", match: "links" },
        { domain: "worldrank.site", match: "rank" },
        { domain: "you-found-the-hidden-link.xyz", match: ".xyz" },
      ],
      seo_manipulation_links: [
        {
          "Domain ascore": "4",
          Domain: "global-ranks.pages.dev",
          Backlinks: "2",
          "IP Address": "172.66.47.146",
          Country: "",
          "First seen": "2025-04-01",
          "Last seen": "2025-12-28",
          _seo_match: "rank",
        },
        {
          "Domain ascore": "6",
          Domain: "kingranks.com",
          Backlinks: "2",
          "IP Address": "66.29.152.77",
          Country: "us",
          "First seen": "2024-12-04",
          "Last seen": "2025-12-23",
          _seo_match: "rank",
        },
        {
          "Domain ascore": "5",
          Domain: "seoprobox.click",
          Backlinks: "2",
          "IP Address": "194.238.28.126",
          Country: "us",
          "First seen": "2025-07-24",
          "Last seen": "2025-08-09",
          _seo_match: "seo",
        },
        {
          "Domain ascore": "2",
          Domain: "takes.sbs",
          Backlinks: "2",
          "IP Address": "147.135.215.43",
          Country: "fr",
          "First seen": "2025-12-12",
          "Last seen": "2026-01-03",
          _seo_match: ".sbs",
        },
        {
          "Domain ascore": "2",
          Domain: "wants.cfd",
          Backlinks: "2",
          "IP Address": "147.135.215.43",
          Country: "fr",
          "First seen": "2025-10-18",
          "Last seen": "2025-12-27",
          _seo_match: ".cfd",
        },
        {
          "Domain ascore": "6",
          Domain: "backlink.co.in",
          Backlinks: "1",
          "IP Address": "184.168.110.97",
          Country: "sg",
          "First seen": "2025-04-12",
          "Last seen": "2026-01-02",
          _seo_match: "backlink",
        },
        {
          "Domain ascore": "0",
          Domain: "backlinkdirectory.site",
          Backlinks: "1",
          "IP Address": "203.161.54.114",
          Country: "us",
          "First seen": "2025-10-15",
          "Last seen": "2025-10-15",
          _seo_match: "backlink",
        },
        {
          "Domain ascore": "6",
          Domain: "backlinks-checker.com",
          Backlinks: "1",
          "IP Address": "195.20.19.178",
          Country: "md",
          "First seen": "2025-05-07",
          "Last seen": "2025-10-05",
          _seo_match: "backlink",
        },
        {
          "Domain ascore": "2",
          Domain: "backlinksources.com",
          Backlinks: "1",
          "IP Address": "184.168.110.97",
          Country: "sg",
          "First seen": "2025-04-02",
          "Last seen": "2025-12-29",
          _seo_match: "backlink",
        },
        {
          "Domain ascore": "5",
          Domain: "best-seo-domains.com",
          Backlinks: "1",
          "IP Address": "104.21.57.160",
          Country: "",
          "First seen": "2025-04-08",
          "Last seen": "2025-07-20",
          _seo_match: "seo",
        },
        {
          "Domain ascore": "2",
          Domain: "blinks.monster",
          Backlinks: "1",
          "IP Address": "147.135.215.43",
          Country: "fr",
          "First seen": "2025-12-08",
          "Last seen": "2025-12-19",
          _seo_match: "links",
        },
        {
          "Domain ascore": "2",
          Domain: "blinks.sbs",
          Backlinks: "1",
          "IP Address": "147.135.215.43",
          Country: "fr",
          "First seen": "2025-12-29",
          "Last seen": "2025-12-29",
          _seo_match: "links",
        },
        {
          "Domain ascore": "4",
          Domain: "boost-your-site-with-homepage-backlinks.us",
          Backlinks: "1",
          "IP Address": "104.21.27.110",
          Country: "",
          "First seen": "2025-07-04",
          "Last seen": "2025-07-04",
          _seo_match: "backlink",
        },
        {
          "Domain ascore": "2",
          Domain: "browse-all-expired-domains.com",
          Backlinks: "1",
          "IP Address": "172.67.149.241",
          Country: "",
          "First seen": "2025-06-28",
          "Last seen": "2025-07-19",
          _seo_match: "expired",
        },
        {
          "Domain ascore": "5",
          Domain: "browseallexpireddomains.us",
          Backlinks: "1",
          "IP Address": "104.21.20.5",
          Country: "",
          "First seen": "2025-05-02",
          "Last seen": "2025-07-07",
          _seo_match: "expired",
        },
        {
          "Domain ascore": "5",
          Domain: "creativeposts.top",
          Backlinks: "1",
          "IP Address": "195.20.19.178",
          Country: "md",
          "First seen": "2025-08-31",
          "Last seen": "2025-08-31",
          _seo_match: ".top",
        },
        {
          "Domain ascore": "5",
          Domain: "dailymusings.top",
          Backlinks: "1",
          "IP Address": "195.20.19.178",
          Country: "md",
          "First seen": "2025-06-20",
          "Last seen": "2025-10-05",
          _seo_match: ".top",
        },
        {
          "Domain ascore": "2",
          Domain: "domains-links-backlinks-all-for-purchase.homes",
          Backlinks: "1",
          "IP Address": "172.67.211.134",
          Country: "",
          "First seen": "2025-04-08",
          "Last seen": "2025-07-06",
          _seo_match: "backlink",
        },
        {
          "Domain ascore": "5",
          Domain: "dr70-links.co.uk",
          Backlinks: "1",
          "IP Address": "172.67.213.93",
          Country: "",
          "First seen": "2025-05-20",
          "Last seen": "2025-07-05",
          _seo_match: "links",
        },
        {
          "Domain ascore": "6",
          Domain: "drjack.world",
          Backlinks: "1",
          "IP Address": "195.20.19.178",
          Country: "md",
          "First seen": "2025-03-10",
          "Last seen": "2025-07-29",
          _seo_match: ".world",
        },
        {
          "Domain ascore": "2",
          Domain: "ever-heard-of-homepage-backlinks.bond",
          Backlinks: "1",
          "IP Address": "172.67.183.164",
          Country: "",
          "First seen": "2025-06-26",
          "Last seen": "2025-07-16",
          _seo_match: "backlink",
        },
        {
          "Domain ascore": "2",
          Domain: "financialvideos.club",
          Backlinks: "1",
          "IP Address": "172.67.207.127",
          Country: "",
          "First seen": "2025-06-28",
          "Last seen": "2025-12-28",
          _seo_match: ".club",
        },
        {
          "Domain ascore": "3",
          Domain: "full-expired-domain-lists.us",
          Backlinks: "1",
          "IP Address": "104.21.32.225",
          Country: "",
          "First seen": "2025-04-01",
          "Last seen": "2025-07-04",
          _seo_match: "expired",
        },
        {
          "Domain ascore": "2",
          Domain: "great-choice-for-pbn-domains.co.uk",
          Backlinks: "1",
          "IP Address": "104.21.92.125",
          Country: "",
          "First seen": "2025-05-06",
          "Last seen": "2025-07-11",
          _seo_match: "pbn",
        },
        {
          "Domain ascore": "5",
          Domain: "indonesia-gov-links.eu",
          Backlinks: "1",
          "IP Address": "104.21.34.6",
          Country: "",
          "First seen": "2025-05-22",
          "Last seen": "2025-07-10",
          _seo_match: "links",
        },
        {
          "Domain ascore": "3",
          Domain: "knows.sbs",
          Backlinks: "1",
          "IP Address": "147.135.215.43",
          Country: "fr",
          "First seen": "2025-11-19",
          "Last seen": "2025-11-19",
          _seo_match: ".sbs",
        },
        {
          "Domain ascore": "7",
          Domain: "linksdirectory.in",
          Backlinks: "1",
          "IP Address": "184.168.110.97",
          Country: "sg",
          "First seen": "2025-04-05",
          "Last seen": "2026-01-08",
          _seo_match: "links",
        },
        {
          "Domain ascore": "5",
          Domain: "metamagic.top",
          Backlinks: "1",
          "IP Address": "195.20.19.178",
          Country: "md",
          "First seen": "2025-06-22",
          "Last seen": "2025-10-14",
          _seo_match: ".top",
        },
        {
          "Domain ascore": "2",
          Domain: "newest-expired-domains-here.click",
          Backlinks: "1",
          "IP Address": "172.67.172.40",
          Country: "",
          "First seen": "2025-07-11",
          "Last seen": "2025-07-11",
          _seo_match: "expired",
        },
        {
          "Domain ascore": "5",
          Domain: "optimizeflow.top",
          Backlinks: "1",
          "IP Address": "195.20.19.178",
          Country: "md",
          "First seen": "2025-07-20",
          "Last seen": "2025-07-20",
          _seo_match: ".top",
        },
        {
          "Domain ascore": "0",
          Domain: "rankingway.site",
          Backlinks: "1",
          "IP Address": "203.161.54.114",
          Country: "us",
          "First seen": "2025-10-15",
          "Last seen": "2025-10-15",
          _seo_match: "rank",
        },
        {
          "Domain ascore": "6",
          Domain: "seo-revealed.club",
          Backlinks: "1",
          "IP Address": "104.21.88.230",
          Country: "",
          "First seen": "2025-06-27",
          "Last seen": "2025-07-17",
          _seo_match: "seo",
        },
        {
          "Domain ascore": "0",
          Domain: "seoboast.site",
          Backlinks: "1",
          "IP Address": "203.161.54.114",
          Country: "us",
          "First seen": "2025-10-16",
          "Last seen": "2025-10-16",
          _seo_match: "seo",
        },
        {
          "Domain ascore": "5",
          Domain: "sunnyside-pbn-domains.club",
          Backlinks: "1",
          "IP Address": "104.21.36.253",
          Country: "",
          "First seen": "2025-04-13",
          "Last seen": "2025-07-22",
          _seo_match: "pbn",
        },
        {
          "Domain ascore": "2",
          Domain: "takes.homes",
          Backlinks: "1",
          "IP Address": "147.135.215.43",
          Country: "fr",
          "First seen": "2025-11-15",
          "Last seen": "2025-11-15",
          _seo_match: ".homes",
        },
        {
          "Domain ascore": "6",
          Domain: "thebestbacklinksavailable.click",
          Backlinks: "1",
          "IP Address": "172.67.145.234",
          Country: "",
          "First seen": "2025-04-24",
          "Last seen": "2025-07-07",
          _seo_match: "backlink",
        },
        {
          "Domain ascore": "6",
          Domain: "webranksite.com",
          Backlinks: "1",
          "IP Address": "104.21.29.59",
          Country: "",
          "First seen": "2024-10-10",
          "Last seen": "2026-01-01",
          _seo_match: "rank",
        },
        {
          "Domain ascore": "0",
          Domain: "webranksofworld.site",
          Backlinks: "1",
          "IP Address": "203.161.54.114",
          Country: "us",
          "First seen": "2025-10-14",
          "Last seen": "2025-10-14",
          _seo_match: "rank",
        },
        {
          "Domain ascore": "2",
          Domain: "what-happens-next.xyz",
          Backlinks: "1",
          "IP Address": "172.67.189.46",
          Country: "",
          "First seen": "2025-04-13",
          "Last seen": "2025-07-11",
          _seo_match: ".xyz",
        },
        {
          "Domain ascore": "4",
          Domain: "who-wants-pbn-links.xyz",
          Backlinks: "1",
          "IP Address": "172.67.130.60",
          Country: "",
          "First seen": "2025-04-18",
          "Last seen": "2025-07-21",
          _seo_match: "links",
        },
        {
          "Domain ascore": "2",
          Domain: "worldclasspbnlinks.biz",
          Backlinks: "1",
          "IP Address": "172.67.216.142",
          Country: "",
          "First seen": "2025-04-12",
          "Last seen": "2025-07-16",
          _seo_match: "links",
        },
        {
          "Domain ascore": "0",
          Domain: "worldrank.site",
          Backlinks: "1",
          "IP Address": "203.161.54.114",
          Country: "us",
          "First seen": "2025-10-15",
          "Last seen": "2025-10-15",
          _seo_match: "rank",
        },
        {
          "Domain ascore": "2",
          Domain: "you-found-the-hidden-link.xyz",
          Backlinks: "1",
          "IP Address": "104.21.35.227",
          Country: "",
          "First seen": "2025-06-25",
          "Last seen": "2025-07-15",
          _seo_match: ".xyz",
        },
      ],
    },
    risky_content_analysis: {
      risky_content_domain_count: 1,
      risky_links_count: 1,
      risky_links_backlinks: 1,
      risky_content_backlinks_percentage: 0.22,
      risky_recent_domains: 0,
      risky_triggered: "No",
      risky_overall_triggered: "No",
      risky_reasoning:
        "The backlink profile does not meet both risk trigger conditions. First, only 0.22% of backlinks come from risky domains, which is far below the required 20% threshold. Second, there is only 1 risky domain (athens-escorts.info, matched for 'escort'), but at least 2 risky domains with recent activity (last seen within 90 days) are needed to trigger a risk. Therefore, since neither condition is satisfied, the risk trigger is not activated.",
      risk_links: [
        {
          "Domain ascore": "4",
          Domain: "athens-escorts.info",
          Backlinks: "1",
          "IP Address": "172.67.179.139",
          Country: "",
          "First seen": "2025-04-12",
          "Last seen": "2025-07-16",
          _risky_match: "escort",
        },
      ],
      risky_matches: [{ domain: "athens-escorts.info", match: "escort" }],
    },
    low_credibility_analysis: {
      low_credibility_domain_count: 5,
      low_credibility_links_count: 17,
      low_credibility_backlinks: 18,
      low_credibility_backlinks_percentage: 3.9,
      low_credibility_avg_domain_authority: 4.529411764705882,
      low_credibility_triggered: "No",
      low_credibility_overall_triggered: "No",
      low_credibility_reasoning:
        "The trigger is not activated because the percentage of backlinks from low-credibility domains with domain authority \u2264 10 is only 3.9%, which is far below the required threshold of 60%. Even though some backlinks come from spammy TLDs such as '.ru', '.pro', and '.info' (for example, miziro.ru, agmermer.pro, and athens-escorts.info), the overall proportion is too low to be considered a significant risk. Both conditions must be met for the trigger to be 'Yes', but here, the first condition (\u2265 60% of backlinks from low-credibility domains with low authority) is not satisfied. Therefore, the trigger is 'No'.",
      low_credibility_domains: [
        { domain: "miziro.ru", match: ".ru" },
        { domain: "agmermer.pro", match: ".pro" },
        { domain: "athens-escorts.info", match: ".info" },
        { domain: "dzj.me", match: ".me" },
        { domain: "fldh.info", match: ".info" },
        { domain: "jacobverghese.info", match: ".info" },
        { domain: "jobsapp.info", match: ".info" },
        { domain: "kompromat100.info", match: ".info" },
        { domain: "mega-remont.pro", match: ".pro" },
        { domain: "moneygame.pro", match: ".pro" },
        { domain: "mundotecnologia.info", match: ".info" },
        { domain: "mydeepin.ru", match: ".ru" },
        { domain: "qa-animals.info", match: ".info" },
        { domain: "sergechel.info", match: ".info" },
        { domain: "worldclasspbnlinks.biz", match: ".biz" },
        { domain: "xubi.me", match: ".me" },
        { domain: "ycm.info", match: ".info" },
      ],
    },
    high_authority_analysis: {
      high_authority_domains_count: 3,
      high_authority_triggered: "Yes",
      high_authority_overall_triggered: "Yes",
      high_authority_reasoning:
        "The backlink profile contains at least one high authority domain from the provided list, which includes tradingview.com (Domain Authority 92), yahoo.com (Domain Authority 100), and google.com (Domain Authority 100). According to the criteria, if at least one high authority domain is present, the trigger is set to Yes. In this case, the high authority domains detected are tradingview.com, yahoo.com, and google.com, all of which have a domain authority score of 70 or higher. Therefore, the condition is met and the trigger is activated.",
      high_authority_domains: [
        { domain: "tradingview.com", domain_authority: 92 },
        { domain: "yahoo.com", domain_authority: 100 },
        { domain: "google.com", domain_authority: 100 },
      ],
    },
    overall_analysis: {
      overall_trigger: "No",
      overall_final_trigger: "No",
      overall_reasoning:
        "The overall trigger is set to 'Yes' only if all four triggers (seo_triggered, risky_triggered, low_credibility_triggered, high_authority_triggered) are activated, or if the first three (seo_triggered, risky_triggered, low_credibility_triggered) are all activated. In this case, only high_authority_triggered is 'Yes', while the others are 'No' or 'False'. Therefore, the conditions for triggering are not met. In simple terms, just having a high authority backlink is not enough to trigger the overall signal; the other risk or SEO-related triggers must also be present.",
    },
    data: [
      {
        "Domain ascore": "92",
        Domain: "tradingview.com",
        Backlinks: "143",
        "IP Address": "3.170.42.43",
        Country: "us",
        "First seen": "2024-03-14",
        "Last seen": "2026-01-08",
      },
      {
        "Domain ascore": "2",
        Domain: "basewebtrading.web.app",
        Backlinks: "31",
        "IP Address": "199.36.158.100",
        Country: "us",
        "First seen": "2024-11-13",
        "Last seen": "2025-11-19",
      },
      {
        "Domain ascore": "2",
        Domain: "ushopwell.com",
        Backlinks: "17",
        "IP Address": "68.66.224.24",
        Country: "us",
        "First seen": "2025-07-10",
        "Last seen": "2026-01-08",
      },
      {
        "Domain ascore": "2",
        Domain: "rsitraining.blogspot.com",
        Backlinks: "16",
        "IP Address": "172.253.122.132",
        Country: "us",
        "First seen": "2024-10-18",
        "Last seen": "2025-12-11",
      },
      {
        "Domain ascore": "31",
        Domain: "freelistingindia.in",
        Backlinks: "8",
        "IP Address": "172.67.155.19",
        Country: "",
        "First seen": "2024-10-06",
        "Last seen": "2025-12-26",
      },
      {
        "Domain ascore": "4",
        Domain: "webalts.com",
        Backlinks: "6",
        "IP Address": "172.67.146.210",
        Country: "",
        "First seen": "2025-10-09",
        "Last seen": "2025-12-31",
      },
      {
        "Domain ascore": "100",
        Domain: "yahoo.com",
        Backlinks: "6",
        "IP Address": "66.218.84.137",
        Country: "us",
        "First seen": "2025-10-03",
        "Last seen": "2025-12-19",
      },
      {
        "Domain ascore": "25",
        Domain: "dailygram.com",
        Backlinks: "5",
        "IP Address": "147.182.143.100",
        Country: "us",
        "First seen": "2025-07-11",
        "Last seen": "2025-08-08",
      },
      {
        "Domain ascore": "100",
        Domain: "google.com",
        Backlinks: "5",
        "IP Address": "142.251.179.100",
        Country: "us",
        "First seen": "2024-12-04",
        "Last seen": "2026-01-02",
      },
      {
        "Domain ascore": "0",
        Domain: "prorsi.blogspot.com",
        Backlinks: "5",
        "IP Address": "172.253.62.132",
        Country: "us",
        "First seen": "2024-11-19",
        "Last seen": "2025-08-17",
      },
      // ... truncated for brevity in sample (full list available in dataset)
    ],
  },

  1021893: {
    seo_analysis: {
      seo_domain_count: 11,
      seo_links_count: 28,
      seo_backlinks: 36,
      seo_backlinks_percentage: 42.86,
      seo_triggered: true,
      seo_overall_triggered: "Yes",
      seo_reasoning:
        "Both conditions for SEO manipulation are met. First, there are 11 domains identified as SEO/backlink-selling/PBN-intent domains (such as 'seo-tip.com' with _seo_match: 'seo', 'wants.cfd' with _seo_match: '.cfd', 'who-wants-pbn-links.xyz' with _seo_match: 'links', and 'sunnyside-pbn-domains.club' with _seo_match: 'pbn'), which is more than the required minimum of 4. Second, these domains account for 36 backlinks, which is 42.86% of the total backlink profile—well above the 30% threshold. Therefore, the backlink profile shows clear evidence of search ranking manipulation based on the defined rule.",
      seo_matches: [
        { domain: "wants.cfd", match: ".cfd" },
        { domain: "seo-tip.com", match: "seo" },
        { domain: "drjack.world", match: ".world" },
        { domain: "knows.sbs", match: ".sbs" },
        { domain: "takes.sbs", match: ".sbs" },
        { domain: "analyticshaven.top", match: ".top" },
        { domain: "backlinks-checker.com", match: "backlink" },
        { domain: "best-seo-domains.com", match: "seo" },
        {
          domain: "boost-your-site-with-homepage-backlinks.us",
          match: "backlink",
        },
        { domain: "browse-all-expired-domains.com", match: "expired" },
        { domain: "browseallexpireddomains.us", match: "expired" },
        {
          domain: "domains-links-backlinks-all-for-purchase.homes",
          match: "backlink",
        },
        { domain: "dr70-links.co.uk", match: "links" },
        { domain: "ever-heard-of-homepage-backlinks.bond", match: "backlink" },
        { domain: "full-expired-domain-lists.us", match: "expired" },
        { domain: "great-choice-for-pbn-domains.co.uk", match: "pbn" },
        { domain: "indonesia-gov-links.eu", match: "links" },
        { domain: "newest-expired-domains-here.click", match: "expired" },
        { domain: "rankvanceboost.pro", match: "rank" },
        { domain: "rankvanceseo.info", match: "seo" },
        { domain: "seo-revealed.club", match: "seo" },
        { domain: "seoflox.io", match: "seo" },
        { domain: "sunnyside-pbn-domains.club", match: "pbn" },
        { domain: "thebestbacklinksavailable.click", match: "backlink" },
        { domain: "what-happens-next.xyz", match: ".xyz" },
        { domain: "who-wants-pbn-links.xyz", match: "links" },
        { domain: "worldclasspbnlinks.biz", match: "links" },
        { domain: "you-found-the-hidden-link.xyz", match: ".xyz" },
      ],
      seo_manipulation_links: [
        {
          "Domain ascore": "2",
          Domain: "wants.cfd",
          Backlinks: "4",
          "IP Address": "147.135.215.43",
          Country: "fr",
          "First seen": "2025-03-28",
          "Last seen": "2025-11-26",
          _seo_match: ".cfd",
        },
        {
          "Domain ascore": "14",
          Domain: "seo-tip.com",
          Backlinks: "3",
          "IP Address": "152.53.38.228",
          Country: "us",
          "First seen": "2025-01-24",
          "Last seen": "2025-07-12",
          _seo_match: "seo",
        },
        {
          "Domain ascore": "25",
          Domain: "drjack.world",
          Backlinks: "2",
          "IP Address": "195.20.19.178",
          Country: "md",
          "First seen": "2025-07-11",
          "Last seen": "2026-01-04",
          _seo_match: ".world",
        },
        {
          "Domain ascore": "3",
          Domain: "knows.sbs",
          Backlinks: "2",
          "IP Address": "147.135.215.43",
          Country: "fr",
          "First seen": "2025-05-20",
          "Last seen": "2025-11-26",
          _seo_match: ".sbs",
        },
        {
          "Domain ascore": "2",
          Domain: "takes.sbs",
          Backlinks: "2",
          "IP Address": "147.135.215.43",
          Country: "fr",
          "First seen": "2025-03-29",
          "Last seen": "2025-11-18",
          _seo_match: ".sbs",
        },
        {
          "Domain ascore": "6",
          Domain: "analyticshaven.top",
          Backlinks: "1",
          "IP Address": "195.20.19.178",
          Country: "md",
          "First seen": "2025-12-06",
          "Last seen": "2025-12-06",
          _seo_match: ".top",
        },
        {
          "Domain ascore": "6",
          Domain: "backlinks-checker.com",
          Backlinks: "1",
          "IP Address": "195.20.19.178",
          Country: "md",
          "First seen": "2025-11-17",
          "Last seen": "2025-11-17",
          _seo_match: "backlink",
        },
        {
          "Domain ascore": "5",
          Domain: "best-seo-domains.com",
          Backlinks: "1",
          "IP Address": "172.67.164.229",
          Country: "",
          "First seen": "2025-01-27",
          "Last seen": "2025-07-20",
          _seo_match: "seo",
        },
        {
          "Domain ascore": "4",
          Domain: "boost-your-site-with-homepage-backlinks.us",
          Backlinks: "1",
          "IP Address": "104.21.27.110",
          Country: "",
          "First seen": "2025-04-07",
          "Last seen": "2025-07-03",
          _seo_match: "backlink",
        },
        {
          "Domain ascore": "2",
          Domain: "browse-all-expired-domains.com",
          Backlinks: "1",
          "IP Address": "104.21.57.208",
          Country: "",
          "First seen": "2025-05-23",
          "Last seen": "2025-07-11",
          _seo_match: "expired",
        },
        {
          "Domain ascore": "5",
          Domain: "browseallexpireddomains.us",
          Backlinks: "1",
          "IP Address": "172.67.190.189",
          Country: "",
          "First seen": "2025-04-29",
          "Last seen": "2025-07-04",
          _seo_match: "expired",
        },
        {
          "Domain ascore": "2",
          Domain: "domains-links-backlinks-all-for-purchase.homes",
          Backlinks: "1",
          "IP Address": "104.21.77.209",
          Country: "",
          "First seen": "2025-04-12",
          "Last seen": "2025-07-16",
          _seo_match: "backlink",
        },
        {
          "Domain ascore": "5",
          Domain: "dr70-links.co.uk",
          Backlinks: "1",
          "IP Address": "172.67.213.93",
          Country: "",
          "First seen": "2025-04-19",
          "Last seen": "2025-07-14",
          _seo_match: "links",
        },
        {
          "Domain ascore": "2",
          Domain: "ever-heard-of-homepage-backlinks.bond",
          Backlinks: "1",
          "IP Address": "104.21.75.238",
          Country: "",
          "First seen": "2025-04-10",
          "Last seen": "2025-07-14",
          _seo_match: "backlink",
        },
        {
          "Domain ascore": "3",
          Domain: "full-expired-domain-lists.us",
          Backlinks: "1",
          "IP Address": "104.21.32.225",
          Country: "",
          "First seen": "2025-04-02",
          "Last seen": "2025-07-20",
          _seo_match: "expired",
        },
        {
          "Domain ascore": "2",
          Domain: "great-choice-for-pbn-domains.co.uk",
          Backlinks: "1",
          "IP Address": "172.67.193.73",
          Country: "",
          "First seen": "2025-04-05",
          "Last seen": "2025-07-04",
          _seo_match: "pbn",
        },
        {
          "Domain ascore": "5",
          Domain: "indonesia-gov-links.eu",
          Backlinks: "1",
          "IP Address": "104.21.34.6",
          Country: "",
          "First seen": "2025-05-22",
          "Last seen": "2025-07-08",
          _seo_match: "links",
        },
        {
          "Domain ascore": "2",
          Domain: "newest-expired-domains-here.click",
          Backlinks: "1",
          "IP Address": "172.67.172.40",
          Country: "",
          "First seen": "2025-06-21",
          "Last seen": "2025-07-11",
          _seo_match: "expired",
        },
        {
          "Domain ascore": "2",
          Domain: "rankvanceboost.pro",
          Backlinks: "1",
          "IP Address": "104.21.1.159",
          Country: "",
          "First seen": "2025-09-22",
          "Last seen": "2025-12-29",
          _seo_match: "rank",
        },
        {
          "Domain ascore": "5",
          Domain: "rankvanceseo.info",
          Backlinks: "1",
          "IP Address": "104.21.56.99",
          Country: "",
          "First seen": "2025-10-04",
          "Last seen": "2025-10-30",
          _seo_match: "seo",
        },
        {
          "Domain ascore": "6",
          Domain: "seo-revealed.club",
          Backlinks: "1",
          "IP Address": "104.21.88.230",
          Country: "",
          "First seen": "2025-06-26",
          "Last seen": "2025-07-16",
          _seo_match: "seo",
        },
        {
          "Domain ascore": "6",
          Domain: "seoflox.io",
          Backlinks: "1",
          "IP Address": "172.67.223.53",
          Country: "",
          "First seen": "2025-03-09",
          "Last seen": "2026-01-08",
          _seo_match: "seo",
        },
        {
          "Domain ascore": "5",
          Domain: "sunnyside-pbn-domains.club",
          Backlinks: "1",
          "IP Address": "104.21.36.253",
          Country: "",
          "First seen": "2025-04-13",
          "Last seen": "2025-07-08",
          _seo_match: "pbn",
        },
        {
          "Domain ascore": "6",
          Domain: "thebestbacklinksavailable.click",
          Backlinks: "1",
          "IP Address": "104.21.95.160",
          Country: "",
          "First seen": "2025-04-28",
          "Last seen": "2025-07-20",
          _seo_match: "backlink",
        },
        {
          "Domain ascore": "2",
          Domain: "what-happens-next.xyz",
          Backlinks: "1",
          "IP Address": "172.67.189.46",
          Country: "",
          "First seen": "2025-05-25",
          "Last seen": "2025-07-13",
          _seo_match: ".xyz",
        },
        {
          "Domain ascore": "4",
          Domain: "who-wants-pbn-links.xyz",
          Backlinks: "1",
          "IP Address": "104.21.3.46",
          Country: "",
          "First seen": "2025-04-23",
          "Last seen": "2025-07-14",
          _seo_match: "links",
        },
        {
          "Domain ascore": "2",
          Domain: "worldclasspbnlinks.biz",
          Backlinks: "1",
          "IP Address": "172.67.216.142",
          Country: "",
          "First seen": "2025-04-30",
          "Last seen": "2025-07-19",
          _seo_match: "links",
        },
        {
          "Domain ascore": "2",
          Domain: "you-found-the-hidden-link.xyz",
          Backlinks: "1",
          "IP Address": "104.21.35.227",
          Country: "",
          "First seen": "2025-04-18",
          "Last seen": "2025-07-08",
          _seo_match: ".xyz",
        },
      ],
    },
    risky_content_analysis: {
      risky_content_domain_count: 1,
      risky_links_count: 1,
      risky_links_backlinks: 1,
      risky_content_backlinks_percentage: 1.19,
      risky_recent_domains: 0,
      risky_triggered: "No",
      risky_overall_triggered: "No",
      risky_reasoning:
        "The backlink profile does not meet both risk trigger conditions. First, only 1.19% of backlinks come from risky domains, which is much less than the required 20%. Second, there is only 1 risky domain ('athens-escorts.info' with the keyword match 'escort'), but at least 2 such domains with recent activity (last seen within 90 days) are needed to trigger a risk. Therefore, since neither condition is satisfied, the risk trigger is not activated.",
      risk_links: [
        {
          "Domain ascore": "4",
          Domain: "athens-escorts.info",
          Backlinks: "1",
          "IP Address": "104.21.43.131",
          Country: "",
          "First seen": "2025-06-19",
          "Last seen": "2025-07-09",
          _risky_match: "escort",
        },
      ],
      risky_matches: [{ domain: "athens-escorts.info", match: "escort" }],
    },
    low_credibility_analysis: {
      low_credibility_domain_count: 4,
      low_credibility_links_count: 17,
      low_credibility_backlinks: 17,
      low_credibility_backlinks_percentage: 20.24,
      low_credibility_avg_domain_authority: 3.7058823529411766,
      low_credibility_triggered: "No",
      low_credibility_overall_triggered: "No",
      low_credibility_reasoning:
        "The trigger is not activated because both conditions are not met. First, only 20.24% of the total backlinks come from low-credibility domains, which is well below the required 60% threshold. Second, while these backlinks do originate from domains with spammy TLDs such as '.pro', '.info', '.me', and '.biz' (for example, 'agmermer.pro', 'athens-escorts.info', 'dzj.me', and 'worldclasspbnlinks.biz'), the percentage of such backlinks is too low to trigger a risk alert. In simple terms, although there are some risky backlinks, they do not make up a large enough portion of the total to be considered a significant threat.",
      low_credibility_domains: [
        { domain: "agmermer.pro", match: ".pro" },
        { domain: "athens-escorts.info", match: ".info" },
        { domain: "dzj.me", match: ".me" },
        { domain: "fldh.info", match: ".info" },
        { domain: "jacobverghese.info", match: ".info" },
        { domain: "jobsapp.info", match: ".info" },
        { domain: "kompromat100.info", match: ".info" },
        { domain: "mega-remont.pro", match: ".pro" },
        { domain: "moneygame.pro", match: ".pro" },
        { domain: "mundotecnologia.info", match: ".info" },
        { domain: "qa-animals.info", match: ".info" },
        { domain: "rankvanceboost.pro", match: ".pro" },
        { domain: "rankvanceseo.info", match: ".info" },
        { domain: "sergechel.info", match: ".info" },
        { domain: "worldclasspbnlinks.biz", match: ".biz" },
        { domain: "xubi.me", match: ".me" },
        { domain: "ycm.info", match: ".info" },
      ],
    },
    high_authority_analysis: {
      high_authority_domains_count: 0,
      high_authority_triggered: "No",
      high_authority_overall_triggered: "No",
      high_authority_reasoning:
        "After analyzing the backlink profile, there are no domains present with a Domain ascore of 70 or higher. The high authority domains list is empty, and the count of unique high authority domains is 0. According to the criteria, a trigger is only activated if at least one high authority domain is detected. Since none are present, the trigger remains 'No'. In simple terms, there are no backlinks from websites considered highly authoritative, so the signal is not triggered.",
      high_authority_domains: [],
    },
    overall_analysis: {
      overall_trigger: "No",
      overall_final_trigger: "No",
      overall_reasoning:
        "The overall trigger is set to 'Yes' only if all four triggers (seo_triggered, risky_triggered, low_credibility_triggered, high_authority_triggered) are true, or if seo_triggered, risky_triggered, and low_credibility_triggered are all true. In this case, only seo_triggered is true, while the other three triggers are false. Therefore, the conditions for an overall trigger are not met. In simple terms, just having one positive signal (SEO) is not enough to activate the overall trigger; more risk or credibility issues would need to be present.",
    },
    data: [
      {
        "Domain ascore": "2",
        Domain: "wants.cfd",
        Backlinks: "4",
        "IP Address": "147.135.215.43",
        Country: "fr",
        "First seen": "2025-03-28",
        "Last seen": "2025-11-26",
        _seo_match: ".cfd",
      },
      {
        "Domain ascore": "14",
        Domain: "seo-tip.com",
        Backlinks: "3",
        "IP Address": "152.53.38.228",
        Country: "us",
        "First seen": "2025-01-24",
        "Last seen": "2025-07-12",
        _seo_match: "seo",
      },
      {
        "Domain ascore": "6",
        Domain: "conference.delhi.in",
        Backlinks: "2",
        "IP Address": "172.67.136.99",
        Country: "",
        "First seen": "2025-03-30",
        "Last seen": "2025-07-16",
      },
      {
        "Domain ascore": "25",
        Domain: "drjack.world",
        Backlinks: "2",
        "IP Address": "195.20.19.178",
        Country: "md",
        "First seen": "2025-07-11",
        "Last seen": "2026-01-04",
        _seo_match: ".world",
      },
      // ... truncated for brevity
    ],
  },
};

export default backlinksSampleData;
